name: 🎨 Windows .NET
on:
  workflow_call:
    inputs:
      fullbuild:
        description: "Whether or not to build all targets"
        required: true
        type: boolean

      godot_version:
        description: "Version of godot to be used"
        required: true
        type: string

env:
  BASE_BRANCH: main
  SCONSFLAGS: "production=yes extra_suffix=luaAPI"
  SCONS_CACHE_LIMIT: 7168
  GODOT_VERSION: ${{ inputs.godot_version }}-stable

jobs:
  windows-builds:
    runs-on: ${{ matrix.opts.runner }}
    name: ${{ matrix.opts.name }}
    strategy:
      fail-fast: false
      matrix:
        opts:
          - name: Windows Editor (target=editor)
            cache-name: windows-mono-editor
            artifact-name: windows-editor
            build-options: "target=editor module_mono_enabled=yes"
            runner: "windows-latest"
            should-run: true

          - name: Windows Editor LuaJIT (target=editor,luaapi_luaver=jit)
            cache-name: windows-mono-editor-luajit
            artifact-name: windows-editor-luajit
            build-options: "target=editor luaapi_luaver=jit debug_symbols=no module_mono_enabled=yes"
            runner: "windows-latest"
            should-run: ${{ inputs.fullbuild }}

          - name: Windows Template (target=template_release,arch=x86_64)
            cache-name: windows-mono-template
            artifact-name: export-templates
            build-options: "target=template_release arch=x86_64 module_mono_enabled=yes"
            runner: "ubuntu-20.04"
            should-run: true # Verify Cross Compile on Check only runs

          - name: Windows Template Debug (target=template_debug,arch=x86_64)
            cache-name: windows-mono-template-debug
            artifact-name: export-templates
            build-options: "target=template_debug arch=x86_64 module_mono_enabled=yes"
            runner: "ubuntu-20.04"
            should-run: ${{ inputs.fullbuild }}

          - name: Windows Template (target=template_release,arch=x86_32)
            cache-name: windows-mono-template
            artifact-name: export-templates
            build-options: "target=template_release arch=x86_32 module_mono_enabled=yes"
            runner: "ubuntu-20.04"
            should-run: ${{ inputs.fullbuild }}

          - name: Windows Template Debug (target=template_debug,arch=x86_32)
            cache-name: windows-mono-template-debug
            artifact-name: export-templates
            build-options: "target=template_debug arch=x86_32 module_mono_enabled=yes"
            runner: "ubuntu-20.04"
            should-run: ${{ inputs.fullbuild }}
        exclude:
          - { opts: { should-run: false } }

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Editing this is pretty dangerous for Windows since it can break.
      # Needs to be properly tested with a fresh cache.
      - name: Load .scons_cache directory
        uses: RevoluPowered/cache@v2.1
        with:
          path: /.scons_cache/
          key: ${{matrix.opts.cache-name}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{matrix.opts.cache-name}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{matrix.opts.cache-name}}-${{env.BASE_BRANCH}}-${{github.ref}}
            ${{matrix.opts.cache-name}}-${{env.BASE_BRANCH}}

      - name: Install mingw64 (Linux)
        if: ${{ matrix.opts.runner != 'windows-latest' }}
        shell: sh
        run: |
          sudo apt update
          sudo apt install gcc-multilib g++-multilib
          sudo apt-get install mingw-w64
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
          sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Configuring Python packages (Windows)
        if: matrix.opts.runner == 'windows-latest'
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons pywin32
          python --version
          scons --version

      - name: Configuring Python packages (Linux)
        if: matrix.opts.runner != 'windows-latest'
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Installing .NET 7.0
        if: matrix.opts.runner == 'windows-latest'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Create local NuGet source
        run: dotnet nuget add source scripts/godot/MyLocalNugetSource --name MyLocalNugetSource

      - name: Compilation
        working-directory: ./scripts
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          scons platform=windows ${{ matrix.opts.build-options }} ${{ env.SCONSFLAGS }}

      - name: Generating the C# glue
        if: matrix.opts.runner == 'windows-latest'
        shell: pwsh
        run: scripts/godot/bin/godot.windows.editor.x86_64.luaAPI.mono.exe --generate-mono-glue scripts/godot/modules/mono/glue

      - name: Build .NET assemblies
        if: matrix.opts.runner == 'windows-latest'
        run: python3 scripts/godot/modules/mono/build_scripts/build_assemblies.py --godot-output-dir=scripts/godot/monobin --godot-platform=windows --push-nupkgs-local scripts/godot/MyLocalNugetSource

      - name: Prepare artifact (Windows)
        if: matrix.opts.runner == 'windows-latest'
        shell: bash
        run: |
          rm -rf scripts/godot/bin/{*.exp,*.lib,*.pdb}

      - name: Prepare artifact (Linux)
        if: matrix.opts.runner != 'windows-latest'
        shell: bash
        run: |
          rm -rf scripts/godot/bin/{*.exp,*.lib,*.pdb}
          strip scripts/godot/bin/*.exe

      - name: Prepare artifact GodotSharp folder
        if: matrix.opts.runner == 'windows-latest'
        shell: bash
        run: mv scripts/godot/monobin/GodotSharp scripts/godot/bin/

      - name: Prepare templates
        if: matrix.opts.artifact-name == 'export-templates'
        shell: bash
        run: |
          mkdir -p scripts/godot/templates

          mv scripts/godot/bin/godot.windows.template_release.x86_64.luaAPI.mono.exe scripts/godot/templates/windows_release_x86_64.mono.exe || true
          mv scripts/godot/bin/godot.windows.template_debug.x86_64.luaAPI.mono.exe scripts/godot/templates/windows_debug_x86_64.mono.exe || true
          mv scripts/godot/bin/godot.windows.template_release.x86_32.luaAPI.mono.exe scripts/godot/templates/windows_release_x86_32.mono.exe || true
          mv scripts/godot/bin/godot.windows.template_debug.x86_32.luaAPI.mono.exe scripts/godot/templates/windows_debug_x86_32.mono.exe || true

          mv scripts/godot/bin/godot.windows.template_release.x86_64.luaAPI.mono.console.exe scripts/godot/templates/windows_release_x86_64_console.mono.exe || true
          mv scripts/godot/bin/godot.windows.template_debug.x86_64.luaAPI.mono.console.exe scripts/godot/templates/windows_debug_x86_64_console.mono.exe || true
          mv scripts/godot/bin/godot.windows.template_release.x86_32.luaAPI.mono.console.exe scripts/godot/templates/windows_release_x86_32_console.mono.exe || true
          mv scripts/godot/bin/godot.windows.template_debug.x86_32.luaAPI.mono.console.exe scripts/godot/templates/windows_debug_x86_32_console.mono.exe || true


          rm -rf scripts/godot/bin/*
          mv scripts/godot/templates scripts/godot/bin/

      - name: Copy License
        if: matrix.opts.artifact-name != 'export-templates'
        shell: bash
        run: |
          cp -n README.md LICENSE scripts/godot/bin/

      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.opts.artifact-name}}
          path: scripts/godot/bin/*

      - uses: actions/upload-artifact@v2
        with:
          name: nuget-packages
          path: scripts/godot/MyLocalNugetSource/*
